name = "telnyx-sms-webhook"
main = "src/webhook.ts"
compatibility_date = "2025-12-17"

[vars]
ENV = "dev"
TELNYX_PUBLIC_KEY_BASE64 = "rlvNR/b+fDa8T8ZquoObb5XdBb6bsnXzF9GG8kWnIV8="

[[queues.producers]]
queue = "sms-events"
binding = "SMS_EVENTS_QUEUE"
